[package]
name = "tt_riing_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
# Async
tokio = { version = "1.45.0", features = ["full"] }

# OS
zbus = { version = "5.6.0", default-features = false, features = ["tokio"] }
hidapi = { version = "2.6" }
daemonize = "0.5"
signal-hook = { version = "0.3", features = ["iterator"] }
event-listener = "5.4.0"

# Config
unconfig = { git = "https://github.com/rojer-98/unconfig.git" }

# Log
syslog = "7.0"
log = "0.4.27"

# Helpers
uuid = { version = "1.7", features = ["v4"] }
anyhow = "1.0"
