use super::HIDAPI;
use crate::config::{
    Config,
    cfg::{ControllerCfg, FanCfg, UsbSelector},
};
use crate::drivers::fan_controller::FanController;
use crate::drivers::tt_riing_quad::TTRiingQuad;
use std::sync::LazyLock;
use tracing::{debug, info, warn};

/// Hardware information returned by controller drivers
#[derive(Debug, Clone)]
pub struct HardwareInfo {
    pub vid: u16,
    pub pids: Vec<u16>,
    pub channel_count: u8,
    pub name: String,
}

/// A controller detected during hardware scan
#[derive(Debug)]
struct DetectedController {
    hardware_info: HardwareInfo,
    detected_pid: u16,
}

impl DetectedController {
    /// Create a new detected controller
    fn new(hardware_info: HardwareInfo, detected_pid: u16) -> Self {
        Self {
            hardware_info,
            detected_pid,
        }
    }

    /// Create fallback configuration for this controller
    fn create_fallback_config(&self) -> ControllerCfg {
        let auto_id = format!(
            "autogenerated-{:04X}-{:04X}",
            self.hardware_info.vid, self.detected_pid
        );

        let fans = (1..=self.hardware_info.channel_count)
            .map(|idx| FanCfg {
                idx,
                name: format!("Fan {idx}"),
            })
            .collect();

        ControllerCfg::RiingQuad {
            id: auto_id,
            usb: UsbSelector {
                vid: self.hardware_info.vid,
                pid: self.detected_pid,
                serial: None,
            },
            fans,
        }
    }
}

/// Registry for controller hardware detection and configuration merging
pub struct Registry;

impl Registry {
    /// Get list of all supported hardware (cached)
    fn get_supported_hardware() -> &'static [HardwareInfo] {
        static SUPPORTED_HARDWARE: LazyLock<Vec<HardwareInfo>> = LazyLock::new(|| {
            vec![
                TTRiingQuad::hardware_info(),
                // Add more controller types here in the future
            ]
        });
        &SUPPORTED_HARDWARE
    }

    /// Scan hardware and merge with existing config
    pub fn merge_with_config(config: &mut Config) {
        debug!("Starting hardware scan and config merge");

        let detected = Self::scan_hardware();

        let added_count = detected.iter().fold(0, |count, detected_controller| {
            if !Self::controller_exists_in_config(&config.controllers, detected_controller) {
                // Add new controller with fallback settings
                let fallback_config = detected_controller.create_fallback_config();
                warn!(
                    "Controller {}:{} (VID:PID {:04X}:{:04X}) not found in configuration, adding with fallback settings",
                    detected_controller.hardware_info.name,
                    Self::get_controller_id(&fallback_config),
                    detected_controller.hardware_info.vid,
                    detected_controller.detected_pid
                );
                config.controllers.push(fallback_config);
                count + 1
            } else {
                count
            }
        });

        if added_count > 0 {
            info!("Added {} controllers to configuration", added_count);
        }
    }

    /// Validate that all controllers in config are supported
    pub fn validate_supported_controllers(config: &Config) -> Vec<String> {
        debug!("Validating controller support in configuration");

        let supported_hardware = Self::get_supported_hardware();

        let unsupported = config
            .controllers
            .iter()
            .filter_map(|cfg| {
                if let Some(usb) = Self::extract_usb_info(cfg) {
                    if !supported_hardware
                        .iter()
                        .any(|hw| hw.vid == usb.vid && hw.pids.contains(&usb.pid))
                    {
                        Some(format!(
                            "Controller '{}' (VID:PID {:04X}:{:04X}) is not supported",
                            Self::get_controller_id(cfg),
                            usb.vid,
                            usb.pid
                        ))
                    } else {
                        None
                    }
                } else {
                    None
                }
            })
            .collect::<Vec<_>>();

        if unsupported.is_empty() {
            info!(
                "All {} controllers in configuration are supported",
                config.controllers.len()
            );
        } else {
            warn!(
                "Found {} unsupported controllers in configuration",
                unsupported.len()
            );
        }

        unsupported
    }

    /// Scan for all supported hardware controllers
    fn scan_hardware() -> Vec<DetectedController> {
        debug!("Starting hardware scan for supported controllers");

        let hidapi = match HIDAPI.as_ref() {
            Some(api) => api,
            None => {
                warn!("HID API not available, skipping hardware scan");
                return Vec::new();
            }
        };

        let device_list = hidapi.device_list();
        let supported_hardware = Self::get_supported_hardware();

        let detected: Vec<DetectedController> = device_list
            .filter_map(|device| {
                supported_hardware.iter().find_map(|hw_info| {
                    if device.vendor_id() == hw_info.vid
                        && hw_info.pids.contains(&device.product_id())
                    {
                        info!(
                            "Detected controller: {} (VID:PID {:04X}:{:04X})",
                            hw_info.name,
                            device.vendor_id(),
                            device.product_id()
                        );
                        Some(DetectedController::new(
                            hw_info.clone(),
                            device.product_id(),
                        ))
                    } else {
                        None
                    }
                })
            })
            .collect();

        info!(
            "Hardware scan completed. Found {} controllers",
            detected.len()
        );
        detected
    }

    /// Check if controller already exists in configuration
    fn controller_exists_in_config(
        controllers: &[ControllerCfg],
        detected: &DetectedController,
    ) -> bool {
        controllers.iter().any(|cfg| {
            Self::extract_usb_info(cfg)
                .map(|usb| {
                    usb.vid == detected.hardware_info.vid && usb.pid == detected.detected_pid
                })
                .unwrap_or(false)
        })
    }

    /// Extract USB information from controller configuration
    fn extract_usb_info(config: &ControllerCfg) -> Option<&UsbSelector> {
        match config {
            ControllerCfg::RiingQuad { usb, .. } => Some(usb),
        }
    }

    /// Get controller ID from configuration
    fn get_controller_id(config: &ControllerCfg) -> &str {
        match config {
            ControllerCfg::RiingQuad { id, .. } => id,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_detected_controller_fallback_config() {
        let hw_info = HardwareInfo {
            vid: 0x264A,
            pids: vec![0x232B, 0x232C],
            channel_count: 4,
            name: "Test Controller".to_string(),
        };

        let detected = DetectedController::new(hw_info, 0x232B);
        let config = detected.create_fallback_config();

        assert_eq!(detected.detected_pid, 0x232B);

        match config {
            ControllerCfg::RiingQuad { id, usb, fans } => {
                assert_eq!(id, "autogenerated-264A-232B");
                assert_eq!(usb.vid, 0x264A);
                assert_eq!(usb.pid, 0x232B);
                assert_eq!(fans.len(), 4);
                assert_eq!(fans[0].name, "Fan 1");
                assert_eq!(fans[3].name, "Fan 4");
            }
        }
    }

    #[test]
    fn test_controller_exists_in_config() {
        let hw_info = HardwareInfo {
            vid: 0x264A,
            pids: vec![0x232B],
            channel_count: 4,
            name: "Test Controller".to_string(),
        };

        let detected = DetectedController::new(hw_info, 0x232B);

        let existing_config = vec![ControllerCfg::RiingQuad {
            id: "existing-controller".to_string(),
            usb: UsbSelector {
                vid: 0x264A,
                pid: 0x232B,
                serial: None,
            },
            fans: vec![],
        }];

        assert!(Registry::controller_exists_in_config(
            &existing_config,
            &detected
        ));

        let different_config = vec![ControllerCfg::RiingQuad {
            id: "different-controller".to_string(),
            usb: UsbSelector {
                vid: 0x264A,
                pid: 0x232C, // Different PID
                serial: None,
            },
            fans: vec![],
        }];

        assert!(!Registry::controller_exists_in_config(
            &different_config,
            &detected
        ));
    }

    #[test]
    fn test_validate_supported_controllers() {
        use crate::config::Config;

        // Test with supported controller
        let supported_config = Config {
            controllers: vec![ControllerCfg::RiingQuad {
                id: "supported-controller".to_string(),
                usb: UsbSelector {
                    vid: 0x264a, // TTRiingQuad VID
                    pid: 0x232B, // TTRiingQuad supported PID
                    serial: None,
                },
                fans: vec![],
            }],
            ..Default::default()
        };

        let errors = Registry::validate_supported_controllers(&supported_config);
        assert!(errors.is_empty());

        // Test with unsupported controller
        let unsupported_config = Config {
            controllers: vec![ControllerCfg::RiingQuad {
                id: "unsupported-controller".to_string(),
                usb: UsbSelector {
                    vid: 0x1234, // Unknown VID
                    pid: 0x5678, // Unknown PID
                    serial: None,
                },
                fans: vec![],
            }],
            ..Default::default()
        };

        let errors = Registry::validate_supported_controllers(&unsupported_config);
        assert_eq!(errors.len(), 1);
        assert!(errors[0].contains("unsupported-controller"));
        assert!(errors[0].contains("1234:5678"));
    }
}
